task: nerf
gpus: [0]
exp_name: 'neus'
scene: 'lego'

train_dataset_module: lib.datasets.neus.neus_dataset
test_dataset_module: lib.datasets.neus.neus_dataset
network_module: lib.networks.neus.network
loss_module: lib.train.losses.neus_loss
evaluator_module: lib.evaluators.neus
visualizer_module: lib.visualizers.img_fit

task_arg:
    N_pixels: 100
    chunk_size: 16384

network:
    n_samples: 64
    n_importance: 64
    n_outside: 0
    up_sample_steps: 4     # 1 for simple coarse-to-fine sampling
    perturb: 1.0
    nerf:
        D: 8
        d_in: 4
        d_in_view: 3
        W: 256
        multires: 10
        multires_view: 4
        output_ch: 4
        skips: [4]
        use_viewdirs: True
    sdf_network:
        d_out: 257
        d_in: 3
        d_hidden: 256
        n_layers: 8
        skip_in: [4]
        multires: 6
        bias: 0.5
        scale: 1.0
        geometric_init: True
        weight_norm: True
        inside_outside: False
    variance_network:
        init_val: 0.3

    rendering_network:
        d_feature: 256
        mode: idr
        d_in: 9
        d_out: 3
        d_hidden: 256
        n_layers: 4
        weight_norm: True
        multires_view: 4
        squeeze_out: True


train_dataset:
    data_dir: '/home/guojun/research/learning_neus/public_data/scan40/'
    render_cameras_name: 'cameras.npz'
    object_cameras_name: 'cameras.npz'
    camera_outside_sphere: True
    scale_mat_scale: 1.1
    data_root: 'data/nerf_synthetic'
    split: 'train'
    view: 0
    input_ratio: 1.
    resolution_level: 1

test_dataset:
    data_dir: '/home/guojun/research/learning_neus/public_data/scan40/'
    render_cameras_name: 'cameras.npz'
    object_cameras_name: 'cameras.npz'
    camera_outside_sphere: True
    scale_mat_scale: 1.1
    data_root: 'data/nerf_synthetic'
    view: 0
    split: 'test'
    input_ratio: 0.5
    resolution_level: 1

train:
    batch_size: 1
    anneal_end: 0
    lr: 5e-4
    weight_decay: 0.
    epoch: 20 # 100 * 500
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 20
    num_workers: 0
    validate_resolution_level: 4
    warm_up_end: 5000
    use_white_bkgd: False
    igr_weight: 0.1
    mask_weight: 0.0

test:
    batch_size: 1

ep_iter: 500
eval_ep: 10       # 50 iterations
save_latest_ep: 20 # 10000 iterations
log_interval: 100
